on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: false
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: true
        type: string

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.print_tags == 'false' }} 
    steps:
      - name: Print the input print tag to STDOUT
        run: echo "The tags are ${{ github.event.inputs.print_tags }}"
  tags:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.print_tags }}
    steps:
      - name: Print the input tags to STDOUT
        run: echo "The tags are ${{ inputs.tags }}"
